### ISSUE TITLE
Bug- handle sentence input #2

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/vigenere_cipher#3]
# handle sentence input
To handle sentence input from the user for decryption.
# Resources
https://www.geeksforgeeks.org/vigenere-cipher/
 <hr>
** Bounty points alloted : 50 ** 
Any further improvements along with bug fixes will be given brownie points. If the countributor sees any further inprovements that can be done to this project ,raise an issue.

**Comment by rithvikjayaram** [comment]
Hey, can I work on this issue?

**Comment by shriyays** [comment]
are you able to access it now? @rithvikjayaram

**Comment by Omicron02** [comment]
Can i be assigned to this pls

**Comment by shriyays** [comment]
> i want to work on this

I'm so sorry but you cannot submit/do anything during the freeze period.

**Comment by RheshaVinod** [comment]
Hey ,can i work on this?

**Comment by Obsarian** [comment]
Hey, can you assign me this issue?
