### ISSUE TITLE
Bug- file encryption

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/vigenere_cipher#4]
# File Handling
# Description
To handle files as input for the encryption function.
File must be stored in the same directory as the .c files for the code to run.
## Resources
https://www.geeksforgeeks.org/vigenere-cipher/
<hr>
**Bounty points alloted : 70**

Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by pranav1st** [comment]
Can i work on this?

**Comment by shriyays** [comment]
> Hi, can I work on this issue?

I'm so sorry but you cannot submit/do anything during the freeze period.

**Comment by Obsarian** [comment]
Can I please work on this issue?

**Comment by shriyays** [comment]
> Can I please work on this issue?

I'm so sorry for the late reply. but youve been assigned to the issue , hope you have fun working on it.

**Comment by Obsarian** [comment]
I have notice many syntax errors in the other .c files of this repo, may I please correct them?

**Comment by shriyays** [comment]
> I have notice many syntax errors in the other .c files of this repo, may I please correct them?

yep!

**Comment by JoyenBenitto** [comment]
hey can I work on this

**Comment by shriyays** [comment]
> hey can I work on this

sos orry for the delay. i've assigned you now . hope you have fun working on it
