### ISSUE TITLE
Bug- file decryption

### ISSUE THREAD

**Issue by karunakc** [acmpesuecc/vigenere_cipher#5]
# File Handling
# Description
To handle files as input for the decryption function.
File must be stored in the same directory as the .c files for the code to run.
## Resources
https://www.geeksforgeeks.org/vigenere-cipher/
<hr>
** Bounty points alloted : 70 **
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by shriyays** [comment]
> Hello, I wish to work on this issue can you please assign this issue to me?

Hey you've been assigned to the issue. Hope you have fun!

**Comment by shriyays** [comment]
> I want to work on this

I'm so sorry but you cannot submit/do anything during the freeze period.

**Comment by CoderCatA5** [comment]
can i work on this?

**Comment by karunakc** [comment]
> can i work on this?

sure!

**Comment by Saieeshsrao** [comment]
can i work on this  issue?

**Comment by jagriti-bhatia** [comment]
> can i work on this issue?

you've been assigned to the issue! go ahead and work on it!
